application: tournatrack
version: testing
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:

- url: /style
  static_dir: static

- url: /favicon.ico
  upload: img/favicon.ico
  static_files: img/favicon.ico

- url: /mod/.*
  script: modify.app

- url: /comms.*
  script: comms.app

- url: /directory
  script: directory.app

- url: /myProfile
  script: profile.app

- url: /myProfile/addSpeakerRecord
  script: add_speaker_record.app

- url: /myProfile/deleteSpeakerRecord
  script: delete_speaker_record.app

- url: /myProfile/addJudgeRecord
  script: add_judge_record.app

- url: /update_profile.*
  script: update_profile.app

- url: /tab
  script: tab.app

- url: /tab/tournaman.*
  script: tournaman.app

- url: /custom_room_status
  script: custom_room_status.app

- url: /delete_status
  script: deletestatus.app

- url: /add_to_reg
  script: reg_add.app

- url: /updateteams
  script: updatereg.app

- url: /updatejudges
  script: updatereg.app

- url: /reg/institution
  script: reginstitution.app

- url: /reg/team
  script: regteam.app

- url: /dereg/.*
  script: dereg.app

- url: /reg/judge
  script: regjudge.app

- url: /reg
  script: reg.app

- url: /toggle_pre_reg
  script: regcontrol.app

- url: /reg_control
  script: regcontrol.app

- url: /delete_tournament
  script: deletetournament.app

- url: /reset_rooms
  script: resetrooms.app

- url: /trackpanel
  script: trackpanel.app

- url: /trackurls
  script: trackurls.app

- url: /trackgrid
  script: trackgrid.app

- url: /trackpin
  script: trackpin.app

- url: /toggle_room
  script: toggleroom.app

- url: /del_r
  script: deleteroom.app

- url: /room
  script: room.app

- url: /del_i
  script: deleteinst.app

- url: /tournaments
  script: tournaments.app

- url: /tournament_instance.*
  script: tournamentinstance.app

- url: /hub.*
  script: hub.app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
